# Generated by Django 2.2 on 2020-12-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relantionship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relantionship',
            new_name='Relationship',
        ),
    ]
